blueprint:
  name: Test (Z2M)
  description: 'Control lights with a Philips Hue Tap Switch. Use the four buttons
    to control up to four light(s) with an on, off or toggle or custom actions.
    Supports short release and long release each beheaviour can 
    configured seperatly.
    The dial can be used to dim the most recently used lights or call a custom 
    rotation action for that button.
    based on 
    apollo1220 - https://github.com/apollo1220/blueprints/blob/main/philips_zigbee_dial.yaml
    gtunes - https://gist.github.com/gtunes-dev/c87168d84292004e760ce697ba1ae6af'
  domain: automation
  input:
    mqtt_topic:
      name: MQTT Topic
      description: Topic of the Philips Hue Tap Dial Switch
      default: zigbee2mqtt/<device name>
    double_press_helper:
      name: (OPTIONAL) Double Press Helper
      description: Boolean helper to detect double press actions. 
      default:
      selector:
        entity:
          domain:
          - input_boolean
          multiple: false
mode: restart
max_exceeded: silent
variables:
  mqtt_topic: !input mqtt_topic
  double_press_helper: !input double_press_helper
  
triggers:
  - topic: !input mqtt_topic
    platform: mqtt
    id: dial-tab_01
condition:
  - condition: template
    value_template: '{{ trigger.payload_json.action != "" }}'
action:
- variables:
    action: '{{ trigger.payload_json.action }}'
